# Generated by Django 4.2.2 on 2023-06-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_coments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coments',
            old_name='text_coment',
            new_name='text_comment',
        ),
    ]
